### ISSUE TITLE
Filling in Seat's devices

### ISSUE THREAD

**Issue by arrowd** [ConsoleKit2/ConsoleKit2#136]
When running `X -seat /org/freedesktop/ConsoleKit/Seat1` on FreeBSD I end up with no input devices working. Digging into X and libinput sources revealed that the "seat0" value is a special one [1]. I haven't figure out how input devices are supposed to get added to ConsoleKit's `Seat1` object.

At the same time I looked into `org.freedektop.login1` D-Bus service on ArchLinux and Rocky Linux and found that the default seat it creates is called `seat0`, which would solve my problem. Maybe ConsoleKit should name its default seat `seat0`? What's the correct fix for this issue?

[1] https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/config/udev.c#L82

**Comment by arrowd** [comment]
And another case: https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/include/hotplug.h#L78

I believe, CK should create a seat named "seat0" as the primary seat. I can provide a patch if this is acceptable.

**Comment by rnagy** [comment]
Please try #138

**Comment by arrowd** [comment]
This is not enough. The value for the `-seat` argument in X.org invocation would still be `/org/freedesktop/ConsoleKit/seat0`. The D-Bus path should be returned as name component from the `ListSeats` method.

**Comment by rnagy** [comment]
> This is not enough. The value for the `-seat` argument in X.org invocation would still be `/org/freedesktop/ConsoleKit/seat0`. The D-Bus path shouldn't be returned as name component from the `ListSeats` method.

correct. that was a bug in ListSeats which is now fixed in the #138

**Comment by arrowd** [comment]
Yes, this change together with https://github.com/ConsoleKit2/ConsoleKit2/pull/137 improves things for SDDM. There are still some problems but they might be on the SDDM side, so I need to debug this further.

Regarding this PR, `org.freedesktop.ConsoleKit.Seat.GetName()` still returns a path, as well as `.name` property. I didn't check signals but they also probably emit D-Bus paths instead of names.

**Comment by rnagy** [comment]
> @rnagy do you plan to further improve this PR? If not let's merge it and will continue on this work.

Yes I am working on this.

**Comment by rnagy** [comment]
Actually my initial commit was kind of wrong, I fixed the root cause of the issue now in #138.

**Comment by arrowd** [comment]
Things looks OK on the ConsoleKit side with these changes. SDDM still doesn't work right, I'll debug this further.

Thanks for working on this, please merge both #138 and #137

**Comment by arrowd** [comment]
Hum, with this change I lost the ability to send my system to hibernation when logging via SDDM. I tracked it down to polkit saying "no", although I'm not sure what exact action does it check:

```
  <action id="org.freedesktop.consolekit.system.hibernate">
    <description>Hibernate the system</description>
    <message>System policy prevents hibernating the system</message>
    <defaults>
      <allow_inactive>no</allow_inactive>
      <allow_active>yes</allow_active>
    </defaults>
  </action>
    
  <action id="org.freedesktop.consolekit.system.hibernate-multiple-users">
    <description>Hibernate the system when multiple users are logged in</description>
    <message>System policy prevents hibernating the system when other users are logged in</message>
    <defaults>
      <allow_inactive>no</allow_inactive>
      <allow_active>auth_admin_keep</allow_active>
    </defaults>
```

Calling `pkcheck` for both actions return "false" for me for some reason. I'll dig deeper, but any hints are appreciated.

**Comment by rnagy** [comment]
Can you show me what output you are getting with pkcheck?

**Comment by rnagy** [comment]
Works fine here with MATE desktop. I think you are missing some polkit policies.

**Comment by arrowd** [comment]
I just noticed that starting X using `startx` with `exec ck-launch-session ...` results in `seat1` being created. This looks wrong.

**Comment by ajacoutot** [comment]
> I just noticed that starting X using `startx` with `exec ck-launch-session ...` results in `seat1` being created. This looks wrong.

You sure you're using the latest tarball?
I think it got rerolled to include https://github.com/ConsoleKit2/ConsoleKit2/commit/dd4bb2f16e0e76a28430ea4d43f5c7a01b6f531c

**Comment by arrowd** [comment]
I'm using `master` branch. I also noticed this change and asked about it there https://github.com/ConsoleKit2/ConsoleKit2/commit/8ff5be2384888a16695f2df8daf0c5812ee20055#r124046914 , but got no answer. I'll try with this change.

**Comment by arrowd** [comment]
Ah, it is already in the `master` branch. I'm using up-to-date code then.

**Comment by arrowd** [comment]
Sorry, I got completely lost in all those commits. That change is indeed missing in `master` and should be there.

**Comment by arrowd** [comment]
Pulling in that change also fixed my problem with polkit authorization. I only wonder why not commit it into `master` in the first place.

I believe this issue can be closed now.

**Comment by rnagy** [comment]
fixed in master as well
