### ISSUE TITLE
ck-1.1.0 cgroups warning

### ISSUE THREAD

**Issue by udeved** [ConsoleKit2/ConsoleKit2#65]
Hi Eric,

On two manjaro and one gentoo system, all running openrc with openrc cgroup support enabled.
Ck version 1.1.0 installed.

I get this warning logged:

    WARNING: Failed to move the session leader process to cgroup, the error was: invalid request

Let me know if you need any further info.

**Comment by udeved** [comment]
I don't know if this is related.
If I run for example kdesu kate, the sockets and root files stuff are created in / instead of /run/user/0

**Comment by EricKoegel** [comment]
Hey!

I created the pull request which should resolve both issues. Let me know if the fixes work.

**Comment by udeved** [comment]
I'll give it a try and will report back.
Thanks, your work is much appreciated.

Btw, is don't know much of the code, but wouldn't it be possible to eventually "backport" multiseat from elogind? Afaik, it don't create cgroups like ck, and I am currently testing it to get a wayland session working.

**Comment by udeved** [comment]
After I included the two patches, the root rundir restrictions disabled thingy seems to work.
I just don't know if a pkexec or kdesu is supposed to create /run/user/0/.. ?
Its not present.

The cpuaccount fallback doesn't seem to work, and the warning is still logged.

**Comment by EricKoegel** [comment]
> I just don't know if a pkexec or kdesu is supposed to create /run/user/0/.. ?

Well if the XDG_RUNTIME_DIR isn't present the software is supposed to fallback to /tmp/ or somewhere else, but I can push that patch since it works and it won't be an issue either way.

> The cpuaccount fallback doesn't seem to work, and the warning is still logged.

Do you get 2 warnings now? What does cat /proc/self/cgroup show?

**Comment by udeved** [comment]
~~~
$ cat /proc/self/cgroup
11:name=systemd:/org/freedesktop/ConsoleKit/Session1
10:pids:/org/freedesktop/ConsoleKit/Session1
9:net_cls:/org/freedesktop/ConsoleKit/Session1
8:freezer:/org/freedesktop/ConsoleKit/Session1
7:devices:/org/freedesktop/ConsoleKit/Session1
6:memory:/org/freedesktop/ConsoleKit/Session1
5:blkio:/org/freedesktop/ConsoleKit/Session1
4:cpuacct:/org/freedesktop/ConsoleKit/Session1
3:cpu:/org/freedesktop/ConsoleKit/Session1
2:cpuset:/org/freedesktop/ConsoleKit/Session1
1:name=openrc:/xdm
~~~

The warning is only once logged.


Snippet of däemon.log right after boot and login:

~~~
Apr 11 08:41:25 manjaro-openrc dbus[1433]: [system] Activating service name='org.freedesktop.UPower' (using servicehelper)
Apr 11 08:41:25 manjaro-openrc dbus[1433]: [system] Successfully activated service 'org.freedesktop.UPower'
Apr 11 09:49:28 manjaro-openrc console-kit-daemon[1460]: WARNING: Failed to move the session leader process to cgroup, the error was: invalid request
Apr 11 09:49:35 manjaro-openrc dbus[1433]: [system] Activating service name='org.kde.powerdevil.backlighthelper' (using servicehelper)
Apr 11 09:49:35 manjaro-openrc dbus[1433]: [system] Successfully activated service
~~~

**Comment by udeved** [comment]
I just read your commit summary.

>Second, if we fail when calling cgmanager_move_pid_abs_sync for the "all" cgroup, we'll still log the >warning but try again with cgmanager_move_pid_abs_sync "cpuacct" which seems to always work.

If I understand correctly, your fix works, but the warning is still logged at first attempt. If it wasn't working, I'd get 2 warnings logged?

**Comment by EricKoegel** [comment]
Correct, I can turn the first warning into a debug to remove those messages. I just wanted to make sure the patches work.

**Comment by archnous** [comment]
Not sure whether this is related or not, but I've recently lost user switching functionality in my boxes, all running openrc, ck2, mate-session-manager-upower and mdm-nosystemd (logout, hibernate, suspend, poweroff, reboot work). Upon clicking on "Logout user" or "Shut Down" in the menu I get "console-kit-daemon: WARNING: Failed to get the session id from cgmanager, the error was: invalid request". This get logged with every click.

```
%  cat /proc/self/cgroup
10:name=systemd:/org/freedesktop/ConsoleKit/Session2
9:bfqio:/org/freedesktop/ConsoleKit/Session2
8:blkio:/org/freedesktop/ConsoleKit/Session2
7:net_cls:/org/freedesktop/ConsoleKit/Session2
6:freezer:/org/freedesktop/ConsoleKit/Session2
5:devices:/org/freedesktop/ConsoleKit/Session2
4:memory:/org/freedesktop/ConsoleKit/Session2
3:cpuset:/org/freedesktop/ConsoleKit/Session2
2:name=openrc:/xdm
```
I'm very short on time, but I could provide any additional info you might request.

**Comment by EricKoegel** [comment]
@udeved  I turned the first warning into a debug message so hopefully that's less confusing.
@archnous 4:cpuacct:/org/freedesktop/ConsoleKit/Session2 is missing from your output and that's what CK2 uses for the lookup. Can you try the pull request #66 ?

**Comment by udeved** [comment]
Hi eric,

I had opportunity to test the patches on the laptop, also running plasma5.
Regarding the rundir root patch, for some weird reasons, I get still sockets for root in / created.
The only difference is the user id for my user on laptop.
I try to figure out whats going on.

**Comment by udeved** [comment]
@EricKoegel 

I believe archnous uses my pkgbuild for archlinux, he likely has latest version from git. :)
If not, pull and rebuild @archnous.

**Comment by EricKoegel** [comment]
I merged the patches into master since it removes the warning and helps with the cgroups stuff. As far as things like kate writing to '/' those patches won't help with that. The problem is that running things like pkexec doesn't launch a new session so the XDG_RUNTIME_DIR doesn't get added to the environment. I'll have to look into it some more.

**Comment by archnous** [comment]
As @udeved pointed out, I'm indeed using his latest pkgbuild and still missing the switch user functionality together with the 4:cpuacct:/org/freedesktop/ConsoleKit/Session2 line from all my archlinux boxen. Please, take a look at the log snippet, the console-kit-daemon warnings appear multiple times and I've uniq'ed them for the sake of brevity. How can I debug this further?
```
Apr 19 18:18:10 hyperion syslog-ng[1387]: syslog-ng starting up; version='3.6.3'
Apr 19 18:18:10 hyperion init[1]: Entering runlevel: 3
Apr 19 18:18:12 hyperion kernel: fuse init (API version 7.23)
Apr 19 18:18:12 hyperion acpid[1830]: starting up with netlink and the input layer
Apr 19 18:18:12 hyperion acpid[1830]: 1 rule loaded
Apr 19 18:18:12 hyperion acpid[1830]: waiting for events: event logging is off
Apr 19 18:18:14 hyperion dbus[1849]: [system] Activating service name='org.freedesktop.PolicyKit1' (using servicehelper)
Apr 19 18:18:16 hyperion polkitd[1977]: Started polkitd version 0.113
Apr 19 18:18:18 hyperion mdm[2036]: Starting mdm...
Apr 19 18:18:19 hyperion acpid[1830]: client connected from 2050[0:0]
Apr 19 18:18:19 hyperion acpid[1830]: 1 client rule loaded
Apr 19 18:18:19 hyperion dbus[1849]: [system] Activating service name='org.freedesktop.ColorManager' (using servicehelper)
Apr 19 18:18:20 hyperion acpid[1830]: client connected from 2050[0:0]
Apr 19 18:18:20 hyperion acpid[1830]: 1 client rule loaded
Apr 19 18:18:20 hyperion dbus[1849]: [system] Successfully activated service 'org.freedesktop.ColorManager'
Apr 19 18:18:22 hyperion dbus[1849]: [system] Successfully activated service 'org.freedesktop.PolicyKit1'
Apr 19 18:18:23 hyperion ag[2095]: mdm-superinit Starting...
Apr 19 18:18:23 hyperion ag[2096]: mdm-superinit Finished
Apr 19 18:18:25 hyperion kernel: NET: Registered protocol family 3
Apr 19 18:18:26 hyperion kernel: b43-phy0: Loading firmware version 666.2 (2011-02-23 01:15:07)
Apr 19 18:18:26 hyperion kernel: IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
Apr 19 18:18:32 hyperion root[2189]: ACPI action undefined: PNP0C0A:00
Apr 19 18:19:31 hyperion mdm-binary[2045]: GLib-CRITICAL: g_key_file_get_string: assertion 'key_file != NULL' failed
Apr 19 18:19:31 hyperion mdm-binary[2045]: GLib-CRITICAL: g_key_file_free: assertion 'key_file != NULL' failed
Apr 19 18:19:50 hyperion acpid[1830]: client 2050[0:0] has disconnected
Apr 19 18:20:07 hyperion console-kit-daemon[1931]: WARNING: Failed to move the session leader process to cgroup, the error was: invalid request
Apr 19 18:20:14 hyperion mate-session[2294]: WARNING: Unable to find provider '' of required component 'dock'
Apr 19 18:20:17 hyperion console-kit-daemon[1931]: WARNING: Failed to get the session id from cgmanager, the error was: invalid request
Apr 19 18:20:17 hyperion dbus[1849]: [system] Activating service name='org.freedesktop.UPower' (using servicehelper)
Apr 19 18:20:17 hyperion dbus[1849]: [system] Successfully activated service 'org.freedesktop.UPower'
Apr 19 18:20:19 hyperion dbus[1849]: [system] Activating service name='org.freedesktop.RealtimeKit1' (using servicehelper)
Apr 19 18:20:19 hyperion dbus[1849]: [system] Successfully activated service 'org.freedesktop.RealtimeKit1'
Apr 19 18:20:22 hyperion dbus[1849]: [system] Activating service name='org.mate.SettingsDaemon.DateTimeMechanism' (using servicehelper)
Apr 19 18:20:22 hyperion dbus[1849]: [system] Successfully activated service 'org.mate.SettingsDaemon.DateTimeMechanism'
Apr 19 18:20:22 hyperion console-kit-daemon[1931]: WARNING: Failed to get the session id from cgmanager, the error was: invalid request
Apr 19 15:20:22 hyperion rtkit-daemon[2465]: Successfully made thread 2463 of process 2463 (/usr/bin/pulseaudio) owned by '1001' high priority at nice level -11.
Apr 19 15:20:22 hyperion rtkit-daemon[2465]: Supervising 1 threads of 1 processes of 1 users.
Apr 19 18:20:22 hyperion console-kit-daemon[1931]: WARNING: Failed to get the session id from cgmanager, the error was: invalid request
Apr 19 18:20:23 hyperion dbus[1849]: [system] Activating service name='org.freedesktop.UDisks2' (using servicehelper)
Apr 19 18:20:23 hyperion udisksd[2534]: udisks daemon version 2.1.6 starting
Apr 19 18:20:23 hyperion dbus[1849]: [system] Successfully activated service 'org.freedesktop.UDisks2'
Apr 19 18:20:23 hyperion udisksd[2534]: Acquired the name org.freedesktop.UDisks2 on the system message bus
Apr 19 18:20:25 hyperion console-kit-daemon[1931]: WARNING: Failed to get the session id from cgmanager, the error was: invalid request
Apr 19 18:21:06 hyperion acpid[1830]: client connected from 2050[0:0]
Apr 19 18:21:06 hyperion acpid[1830]: 1 client rule loaded
Apr 19 18:21:06 hyperion console-kit-daemon[1931]: WARNING: Failed to get the session id from cgmanager, the error was: invalid request
```

**Comment by udeved** [comment]
@archnous 
My last test with mate and no logind proved to be unstable.
I stopped fiddling with gtk stuff except xfce, which works with ck.
Cinnamon also has some ck fallback support.

**Comment by archnous** [comment]
What's really bugging me is the missing 4:cpuacct from /proc/self/cgroup in archlinux. My manjaro-openrc boxes all have it as expected. On the other hand, the no switch-user situation seems to be mate-session or mdm specific as it won't work in manjaro too.

**Comment by udeved** [comment]
What I can tell, for example lxqt seems to have logind depend code, and power management does not work with ck2.
But, I found elogind makes it work naturally. You may try with mate and see if it unlocks the stuff too.

**Comment by Calrama** [comment]
> Hi Eric,
> 
> On two manjaro and one gentoo system, all running openrc with openrc cgroup support enabled.
> Ck version 1.1.0 installed.

This probably happens because you don't tell cgmanager to ignore the OpenRC subsystem/controller. See also the [PR](https://github.com/ConsoleKit2/ConsoleKit2/pull/61) implementing this, where I did mention that. On Gentoo/Funtoo, try to patch your `/etc/init.d/cgmanager` to read `command_args="-m name=systemd -M name=openrc"`

**Comment by udeved** [comment]
Hi eric,

can I help you testing?
Is the session-controller branch WIP or sort of ready?

**Comment by EricKoegel** [comment]
I just started the session-controller stuff so it'll be a little while longer. I'll let you know. I still need to fix up the cgroups stuff too... :)

**Comment by archnous** [comment]
I had implemented @Calrama's fix and forgotten about it (because it had worked :)
Yesterday I bumped again into this cgroups warning along  with absent suspend/hibernate actions in MATE, on another box. Replaced "-m name=systemd" with "-m name=openrc" and got rid of the warning and those upower actions back.
